version: '3.8'

services:
  oneklik-api:
    build: .
    image: oneklik-ai:latest
    container_name: oneklik_ai_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
