// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend/auth"
	"backend/client"
	"backend/config"
	"backend/controller"
	"backend/database"
	"backend/model"
	"backend/repository"
	"backend/service"
	"context"
	"github.com/google/wire"
	"github.com/rs/zerolog/log"
	"go.mongodb.org/mongo-driver/mongo"
	"golang.org/x/oauth2"
)

// Injectors from wire.go:

func InitializeApp(sysCfg *config.SystemConfigs) (*App, func(), error) {
	isProduction := provideIsProduction(sysCfg)
	database, cleanup := provideMongoDatabase(sysCfg)
	configService := service.NewConfigService(database, isProduction)
	configManager, cleanup2 := provideConfigManager(configService)
	healthController := controller.NewHealthController()
	brevoClient := provideBrevoClient()
	emailService := service.NewEmailService(brevoClient, configManager)
	emailController := controller.NewEmailController(emailService)
	marginRepository := repository.NewMarginRepository(database)
	optionRepository := repository.NewOptionRepository(database)
	marginService := service.NewMarginService(marginRepository, configManager, optionRepository)
	marginController := controller.NewMarginController(marginService)
	strategyRepository := repository.NewStrategyRepository(database)
	strategyService := service.NewStrategyService(strategyRepository)
	strategyController := controller.NewStrategyController(strategyService, isProduction)
	chartinkClient := provideChartinkClient()
	yahooClient := provideYahooClient()
	nseService := service.NewNseService(yahooClient)
	chartInkService := service.NewChartInkService(chartinkClient, marginService, nseService)
	chartInkController := controller.NewChartInkController(chartInkService, strategyService)
	userRepository := repository.NewUserRepository(database)
	userService := service.NewUserService(userRepository)
	otpService := service.NewOtpService(emailService, configManager)
	oauth2Config := provideGoogleOAuthConfig(configManager)
	oAuthService := service.NewOAuthService(userService, configManager, isProduction, oauth2Config)
	authService := service.NewAuthService(userService, otpService, isProduction)
	authController := controller.NewAuthController(userService, configManager, otpService, isProduction, oAuthService, authService)
	userController := controller.NewUserController(userService, isProduction, otpService)
	nseController := controller.NewNseController(nseService)
	configController := controller.NewConfigController(configService, isProduction)
	priceActionRepo := repository.NewPriceActionRepo(database)
	priceActionService := service.NewPriceActionService(chartInkService, nseService, priceActionRepo, marginService)
	priceActionController := controller.NewPriceActionController(priceActionService, isProduction)
	genAiClient := provideGenAiClient(configManager)
	newsService := service.NewNewsService(genAiClient, nseService)
	newsController := controller.NewNewsController(newsService)
	zerodhaService := service.NewZerodhaService(userService)
	zerodhaController := controller.NewZerodhaController(zerodhaService, isProduction, userService)
	orderRepo := repository.NewOrderRepo(database)
	angelOneConfig := provideAngelOneConfig(configManager)
	angelOneWebSocket, cleanup3 := provideAngelOneWebSocket(angelOneConfig)
	angelOneService := service.NewAngelOneService(angelOneConfig, angelOneWebSocket)
	orderService := service.NewOrderService(orderRepo, zerodhaService, angelOneService, angelOneWebSocket)
	orderController := controller.NewOrderController(orderService, isProduction)
	angelOneController := controller.NewAngelOneController(angelOneService, isProduction, angelOneWebSocket)
	mstockService := service.NewMstockService(angelOneWebSocket, userService)
	mstockController := controller.NewMstockController(mstockService, isProduction)
	strategyOrderRepository := repository.NewStrategyOrderRepository(database)
	strategyTradingService := service.NewStrategyTradingService(chartInkService, strategyService, strategyOrderRepository, angelOneWebSocket, zerodhaService)
	strategyTradingController := controller.NewStrategyTradingController(strategyTradingService)
	strategyOrderService := service.NewStrategyOrderService(strategyOrderRepository)
	strategyOrderController := controller.NewStrategyOrderController(strategyOrderService, isProduction)
	app := SetupRouterWrapper(isProduction, configManager, healthController, emailController, marginController, strategyController, chartInkController, authController, userController, nseController, configController, priceActionController, newsController, zerodhaController, orderController, angelOneController, mstockController, strategyTradingController, strategyOrderController, marginService, strategyService, angelOneService, angelOneWebSocket)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideIsProduction(sysCfg *config.SystemConfigs) service.IsProduction {
	return service.IsProduction(sysCfg.Config.Environment == "production")
}

func provideMongoDatabase(sysCfg *config.SystemConfigs) (*mongo.Database, func()) {
	client, db := database.InitMongoClient(sysCfg)
	cleanup := func() {
		if err := client.Disconnect(context.Background()); err != nil {
			log.Error().Err(err).Msg("Failed to disconnect MongoDB")
		} else {
			log.Info().Msg("MongoDB disconnected successfully")
		}
	}
	return db, cleanup
}

func provideConfigManager(cfgSvc service.ConfigService) (*config.ConfigManager, func()) {
	cm := cfgSvc.GetConfigManager()
	auth.SecretKey = []byte(cm.GetConfig().JwtSecret)
	database.InitRedis(cm.GetConfig().RedisUrl)
	cleanup := func() {
		if database.RedisHelper != nil {
			database.RedisHelper.
				Close()
			log.Info().Msg("Valkey/Redis connection closed")
		}
	}
	return cm, cleanup
}

func provideAngelOneConfig(cm *config.ConfigManager) *model.AngelOneConfig {
	return &cm.GetConfig().AngelOneConfig
}

func provideGoogleOAuthConfig(cm *config.ConfigManager) *oauth2.Config {
	return auth.GetGoogleOAuthConfig(cm.GetConfig().GoogleAuth)
}

func provideBrevoClient() *client.BrevoClient { return client.NewBrevoClient() }

func provideChartinkClient() *client.ChartinkClient { return client.NewChartinkClient() }

func provideYahooClient() *client.YahooClient { return client.NewYahooClient() }

func provideGenAiClient(cm *config.ConfigManager) *client.GenAiClient {
	return client.NewGenAiClient(cm.GetConfig().GoogleAuth)
}

func provideAngelOneWebSocket(conf *model.AngelOneConfig) (service.AngelOneWebSocket, func()) {
	ws := service.NewAngelOneWebSocket("", "", conf)
	cleanup := func() {
		ws.Disconnect()
		log.Info().Msg("Angel One WebSocket disconnected")
	}
	return ws, cleanup
}

var RepositorySet = wire.NewSet(repository.NewUserRepository, repository.NewMarginRepository, repository.NewStrategyRepository, repository.NewPriceActionRepo, repository.NewOrderRepo, repository.NewOptionRepository, repository.NewStrategyOrderRepository)

var ServiceSet = wire.NewSet(service.NewConfigService, service.NewEmailService, service.NewOtpService, service.NewUserService, service.NewMarginService, service.NewStrategyService, service.NewNseService, service.NewChartInkService, service.NewPriceActionService, service.NewOAuthService, service.NewAuthService, service.NewNewsService, service.NewZerodhaService, service.NewAngelOneService, service.NewOrderService, service.NewMstockService, service.NewStrategyTradingService, service.NewStrategyOrderService)

var ControllerSet = wire.NewSet(controller.NewHealthController, controller.NewEmailController, controller.NewMarginController, controller.NewStrategyController, controller.NewChartInkController, controller.NewAuthController, controller.NewUserController, controller.NewNseController, controller.NewConfigController, controller.NewPriceActionController, controller.NewNewsController, controller.NewZerodhaController, controller.NewOrderController, controller.NewAngelOneController, controller.NewMstockController, controller.NewStrategyTradingController, controller.NewStrategyOrderController)
