// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates user and returns user details without password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login Credentials (only email/password required)",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful (Passwords omitted)",
                        "schema": {
                            "$ref": "#/definitions/model.UserDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clears the authentication cookie to log out the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "message: Logged out successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Retrieves user details (email and role) from the session cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current authenticated user",
                "responses": {
                    "200": {
                        "description": "User details successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/model.UserDto"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Session invalid or expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Stores user data in local memory for 5 minutes and sends an OTP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Signup",
                "parameters": [
                    {
                        "description": "User Registration Details",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/verify-otp": {
            "post": {
                "description": "Validates the OTP from cache. If valid, creates the user in the database and returns a JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify OTP and Create User",
                "parameters": [
                    {
                        "description": "OTP Verification Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VerifyOtpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid OTP or session expired",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    }
                }
            }
        },
        "/chartink/fetch": {
            "get": {
                "description": "Triggers a scan on ChartInk for the given strategy and returns raw stock data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChartInk"
                ],
                "summary": "Fetch raw ChartInk data",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Bullish_Engulfing",
                        "description": "Name of the strategy to run",
                        "name": "strategy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StockData"
                            }
                        }
                    },
                    "404": {
                        "description": "Strategy not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/chartink/fetchWithMargin": {
            "get": {
                "description": "Triggers a scan and maps the results with the current margin and leverage data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChartInk"
                ],
                "summary": "Fetch ChartInk data with Margin info",
                "parameters": [
                    {
                        "type": "string",
                        "example": "Nifty_50_Breakout",
                        "description": "Name of the strategy to run",
                        "name": "strategy",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StockMarginDto"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "Returns the current system settings (Leverage, API Keys, etc.) from the real-time cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Get Active Configuration",
                "responses": {
                    "200": {
                        "description": "Current active config",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.MongoEnvConfig"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Triggers a fresh fetch from MongoDB to update the in-memory cache across all services.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Reload System Configuration",
                "responses": {
                    "200": {
                        "description": "Successfully reloaded",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates the configuration document in MongoDB and hot-swaps the active memory pointer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Update System Configuration",
                "parameters": [
                    {
                        "description": "Update Config Fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MongoEnvConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid Request Body",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/email/send": {
            "post": {
                "description": "Sends a transactional email using the Brevo API provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Send an email",
                "parameters": [
                    {
                        "description": "Email content and recipients",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BrevoEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to send email",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Confirm that the server is up and running. Returns a 200 status code with no body.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "System Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "head": {
                "description": "Confirm that the server is up and running. Returns a 200 status code with no body.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "System Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/margin/all": {
            "get": {
                "description": "Returns a list of all stock margins stored in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Margin"
                ],
                "summary": "Get all margins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Margin"
                            }
                        }
                    }
                }
            }
        },
        "/margin/load-from-csv": {
            "post": {
                "description": "Uploads a CSV file to bulk load or update margin data",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Margin"
                ],
                "summary": "Upload Margin CSV",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Margin CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/margin/reload": {
            "get": {
                "description": "Forces a reload of all margins from the persistent database into the memory cache",
                "tags": [
                    "Margin"
                ],
                "summary": "Reload margins",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/margin/{symbol}": {
            "get": {
                "description": "Fetches the margin details for a specific stock symbol",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Margin"
                ],
                "summary": "Get margin by symbol",
                "parameters": [
                    {
                        "type": "string",
                        "example": "RELIANCE",
                        "description": "Stock Symbol",
                        "name": "symbol",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Margin"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/nse/allindices": {
            "get": {
                "description": "Fetches the latest all indices performance data. Uses a warmup time-cache strategy to serve data efficiently and avoid NSE rate limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Get NSE Sectoral Heatmap",
                "responses": {
                    "200": {
                        "description": "Fetch Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.AllIndicesResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/nse/heatmap": {
            "get": {
                "description": "Fetches the latest sectoral index performance data. Uses a warmup time-cache strategy to serve data efficiently and avoid NSE rate limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Get NSE Sectoral Heatmap",
                "responses": {
                    "200": {
                        "description": "Fetch Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.SectorData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/nse/history": {
            "get": {
                "description": "Fetches stock history for a specific symbol (e.g., BEL). Data is cached for 1 hour.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Get Historical Stock Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock Symbol (e.g. BEL)",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Fetch Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.NSEHistoricalData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/strategy": {
            "get": {
                "description": "Returns a list of all configured trading strategies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Strategy"
                ],
                "summary": "Get all strategies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StrategyDto"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the configuration of an existing strategy by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Strategy"
                ],
                "summary": "Update a strategy",
                "parameters": [
                    {
                        "description": "Updated Strategy Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StrategyDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Strategy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Saves a new trading strategy configuration to the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Strategy"
                ],
                "summary": "Create a strategy",
                "parameters": [
                    {
                        "description": "Strategy Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.StrategyDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Strategy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a strategy from the system using its ID (Name)",
                "tags": [
                    "Strategy"
                ],
                "summary": "Delete a strategy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Strategy ID (Name)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/strategy/admin": {
            "get": {
                "description": "Returns a list of all configured trading strategies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Strategy"
                ],
                "summary": "Get all strategies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.StrategyDto"
                            }
                        }
                    }
                }
            }
        },
        "/strategy/reload": {
            "post": {
                "description": "Syncs the in-memory strategy cache with the MongoDB database",
                "tags": [
                    "Strategy"
                ],
                "summary": "Reload strategies",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/theme": {
            "patch": {
                "description": "Updates the theme preference (LIGHT/DARK) for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Update User Theme",
                "parameters": [
                    {
                        "description": "Theme Preference",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateThemeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/user/username": {
            "patch": {
                "description": "Updates the username and returns the updated user object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update Username",
                "parameters": [
                    {
                        "description": "Target Email and New Username",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AllIndicesResponse": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "string"
                },
                "indexSymbol": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "last": {
                    "type": "number"
                },
                "oneWeekAgoVal": {
                    "type": "number"
                },
                "perChange1w": {
                    "type": "number"
                },
                "perChange30d": {
                    "type": "number"
                },
                "perChange365d": {
                    "type": "number"
                },
                "percentChange": {
                    "type": "number"
                }
            }
        },
        "model.BrevoEmailRequest": {
            "type": "object",
            "properties": {
                "htmlContent": {
                    "type": "string"
                },
                "sender": {
                    "$ref": "#/definitions/model.Recipient"
                },
                "subject": {
                    "type": "string"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Recipient"
                    }
                }
            }
        },
        "model.Margin": {
            "type": "object",
            "properties": {
                "margin": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "model.MessageResponse": {
            "description": "Standard response containing status and a descriptive message",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message provides details about the operation result",
                    "type": "string",
                    "example": "Otp sent successfully to user@example.com"
                },
                "otpSent": {
                    "description": "OtpSent indicates if the OTP was successfully triggered",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "model.MongoEnvConfig": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "brevoApiKey": {
                    "type": "string"
                },
                "brevoEmail": {
                    "type": "string"
                },
                "debug": {
                    "type": "boolean"
                },
                "frontendUrl": {
                    "type": "string"
                },
                "jwtSecret": {
                    "type": "string"
                },
                "leverage": {
                    "type": "number"
                },
                "rateLimiter": {
                    "type": "boolean"
                }
            }
        },
        "model.NSEHistoricalData": {
            "type": "object",
            "properties": {
                "chClosingPrice": {
                    "type": "number"
                },
                "chOpeningPrice": {
                    "type": "number"
                },
                "chSymbol": {
                    "type": "string"
                },
                "chTradeHighPrice": {
                    "type": "number"
                },
                "chTradeLowPrice": {
                    "type": "number"
                },
                "mtimestamp": {
                    "type": "string"
                }
            }
        },
        "model.Recipient": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string",
                    "example": "Update successful"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "model.SectorData": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "current": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "index": {
                    "type": "string"
                },
                "indexLongName": {
                    "type": "string"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "pChange": {
                    "type": "number"
                },
                "timeStamp": {
                    "type": "string"
                }
            }
        },
        "model.StockData": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "nsecode": {
                    "type": "string"
                }
            }
        },
        "model.StockMarginDto": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "margin": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "model.Strategy": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "scanClause": {
                    "type": "string"
                }
            }
        },
        "model.StrategyDto": {
            "type": "object",
            "required": [
                "name",
                "scanClause"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "scanClause": {
                    "type": "string"
                }
            }
        },
        "model.UpdateThemeRequest": {
            "type": "object",
            "required": [
                "theme"
            ],
            "properties": {
                "theme": {
                    "enum": [
                        "LIGHT",
                        "DARK"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.UserTheme"
                        }
                    ],
                    "example": "DARK"
                }
            }
        },
        "model.UserDto": {
            "type": "object",
            "required": [
                "confirmPassword",
                "email"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.UserRole"
                },
                "theme": {
                    "$ref": "#/definitions/model.UserTheme"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.UserRole": {
            "description": "ADMIN or USER access level",
            "type": "string",
            "enum": [
                "ADMIN",
                "USER"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleUser"
            ]
        },
        "model.UserTheme": {
            "description": "LIGHT or DARK theme mode",
            "type": "string",
            "enum": [
                "LIGHT",
                "DARK"
            ],
            "x-enum-varnames": [
                "ThemeLight",
                "ThemeDark"
            ]
        },
        "model.VerifyOtpRequest": {
            "type": "object",
            "required": [
                "email",
                "otp"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Trades Management API",
	Description:      "This is a specialized server for managing trading strategies and margins.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
